### ISSUE TITLE
H1 spacing

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-minimal-header-design#94]
Hey @SteveALee
It looks like the H1 got moved closer to the header.
**That messes up the spacing-proximity** from my perspective.
The header and nav/pager go together.
The h1 goes with the content below.
I do think that should be fixed before we publish this iteration.

![image](https://user-images.githubusercontent.com/6991814/159074326-7eba484e-61b6-4e99-bc6d-8ab1d11d1d4b.png)

(related issue on h2s https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/93 could wait until later iteration)

**Comment by SteveALee** [comment]
That's very strange. Perhaps moving the CSS to the theme caused it due to
order.

**Comment by SteveALee** [comment]
Hmm I'm see more spacing before H1, but also a lot after 
![image](https://user-images.githubusercontent.com/618922/159470545-64b0eee4-1f9d-4d93-848e-e4125350c4e7.png)

**Comment by SteveALee** [comment]
I restored the top spacing. The H2 top margin is unchanged but I can reduce

![image](https://user-images.githubusercontent.com/618922/159475363-8c2075c2-df57-49b8-a4c1-e7bb5cad2716.png)
