### ISSUE TITLE
Complementary region for help improve this page is missing accessible name

### ISSUE THREAD

**Issue by mcking65** [w3c/wai-minimal-header-design#97]
The complementary region containing the "Help Improve This Page" content needs an accessible name.

It often contains a heading that could be referenced by aria-labelledby. However, that heading is longer than necessary. Another option would be to name it "feedback".

~~~
<div aria-label="feedback" role="complementary">
  <H2>Help Improve This Page</h2>
  ...
</div>
~~~

**Comment by mcking65** [comment]
Note: when using aria-label, you need to make sure the aria-label values get translated. They're sometimes overlooked during translation. That is one advantage of aria-labelledby if there is potential for lossy translation processes.

However, aria-label is already used elsewhere in the template, so this may not be a material concern.

**Comment by shawna-slh** [comment]
@stevealee Would you be able to implement this in the main site component? ```aria-label="feedback"``` seems good to me.

**Comment by SteveALee** [comment]
The code used to create this section uses the [box include](https://wai-website-theme.netlify.app/components/boxes/#help-improve-this-page) and it has limited features.

However, the markup I see has an "aside" as the outer container not a div as shown above.

I think this needs more discussion. Can we not make the existing markup more universal rather than adding AT specific markup? Does the heading in the aside not work well with screen readers for example?

@shawna-slh  @mcking65

**Comment by shawna-slh** [comment]
I did some more reading on the topic, including:
> The complementary landmark role...<br>If possible, use the [HTML ```<aside>``` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside) instead.

&mdash; from [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/complementary_role)

I look forward to @mcking65 's input on the option of keeping it simple with just the ```<aside>``` and ```<h2>``` and not needing to add aria-labelledby

**Comment by mcking65** [comment]
using aside is fine; just add aria-label="feedback"

**Comment by SteveALee** [comment]
Will be fixed next time APG is built

**Comment by SteveALee** [comment]
Can this be closed now?

**Comment by shawna-slh** [comment]
I hadn't published it site-wide yet. Just did. It's working on the pages I tested. Thanks Steve!

**Comment by mcking65** [comment]
yes, thank you @SteveALee!

And thank you @shawna-slh for deploying it. I verified the improvement!
